shop/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('orders/', include('orders.urls',namespace='orders')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns = [
      path('',views.HomeView.as_view(),name='home'),
      path('category/<slug:category_slug>/',views.HomeView.as_view(),name='category_filter'),
      path('<slug:slug>/',views.ProductDetailView.as_view(),name='product_detail'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name='orders'
urlpatterns=[
      path('create/',views.OrderCreateView.as_view(),name='order_create'),
      path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
      path('carts/',views.CartView.as_view(),name='cart'),
      path('carts/add/<int:product_id>',views.CartAddView.as_view(),name='cart_add'),
      path('carts/remove/<int:product_id>',views.CartRemoveView.as_view(),name='cart_remove'),
      path('apply/<int:order_id>/',views.CouponApplyView.as_view(),name='apply_coupon'),
]

shop/home/models.py
from django.urls import reverse
from django.db import models




class Category(models.Model):
      sub_category=models.ForeignKey('self', on_delete=models.CASCADE,related_name='scategory',null=True,blank=True)
      is_sub=models.BooleanField(default=False)
      name=models.CharField(max_length=200)
      slug=models.SlugField(max_length=200,unique=True)
      class Meta:
            ordering=('name',)
            verbose_name='category'
            verbose_name_plural='categories'

      def __str__(self):
            return self.name

      def get_absolute_url(self):
            return reverse('home:category_filter',args=[self.slug,])


class Product(models.Model):
      category=models.ManyToManyField(Category,related_name='products')
      name = models.CharField(max_length=200)
      slug=models.SlugField(max_length=200,unique=True)
      image=models.ImageField(upload_to='products/%Y/%m/%d/')
      description=models.TextField()
      price=models.IntegerField()
      available=models.BooleanField(default=True)
      created=models.DateTimeField(auto_now_add=True)
      updated=models.DateTimeField(auto_now=True)

      class Meta:
            ordering=('name',)

      def __str__(self):
            return self.name
      
      def get_absolute_url(self):
            return reverse('home:product_detail',args=[self.slug,])

shop/home/views.py
from itertools import product
from unicodedata import category
from django.shortcuts import render,get_object_or_404
from django.views import View
from .models import Product,Category
from orders.forms import CartAddForm

class HomeView(View):
      def get(self, request,category_slug=None):
            products=Product.objects.filter(available=True)
            categories=Category.objects.filter(is_sub=False)
            if category_slug:
                  category=Category.objects.get(slug=category_slug)
                  products=products.filter(category=category)
            return render(request,'home/home.html',{'products':products,'categories':categories})

class ProductDetailView(View):
      def get(self,request,slug):
            product=get_object_or_404(Product,slug=slug)
            form=CartAddForm()
            return render(request,'home/detail.html',{'product':product,'form':form})

shop/home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}

      <h2>{{product.name}}</h2>
      <small>{{product.created}}</small>
      <p>{{product.price}} Toman </p>
      <img style="width:300px;height: 300px;" src="{{product.image.url}}" alt="">
      <p>{{product.description}}</p>

    
            <form action="{% url 'orders:cart_add' product.id %}" method="post">
                  {% csrf_token %}
                  {{form}}
                  <input type="submit" value="Add to cart">
            </form>
   

{% endblock %}

shop/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}


{% block extra_headers %} 
      <link rel="stylesheet" href="{% static 'home/css/styles.css' %}">
{% endblock %}


{% block content %}

      {% for category in categories %}
            
      <div class="btn-group">
            <a href="{{category.get_absolute_url}}" class="btn btn-danger">{{category.name}}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                  {% for sub in category.scategory.all %}
                         <li><a class="dropdown-item" href="{{sub.get_absolute_url}}">{{sub.name}}</a></li>
                  {% endfor %}
            </ul>
      </div>
    


            
      {% endfor %}
      <br>
      {% for product in products %}
            <div class="card" style="width: 18rem; display: inline-block;">
                  <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
                  <div class="card-body">
                        <a href="{{ product.get_absolute_url }}" class="card-title">{{product.name}}</a>
                  </div>
            </div>
      {% endfor %}
{% endblock %}