shop/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('orders/', include('orders.urls',namespace='orders')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns = [
      path('',views.HomeView.as_view(),name='home'),
      path('category/<slug:category_slug>/',views.HomeView.as_view(),name='category_filter'),
      path('<slug:slug>/',views.ProductDetailView.as_view(),name='product_detail'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name='orders'
urlpatterns=[
      path('create/',views.OrderCreateView.as_view(),name='order_create'),
      path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
      path('carts/',views.CartView.as_view(),name='cart'),
      path('carts/add/<int:product_id>',views.CartAddView.as_view(),name='cart_add'),
      path('carts/remove/<int:product_id>',views.CartRemoveView.as_view(),name='cart_remove'),
      path('apply/<int:order_id>/',views.CouponApplyView.as_view(),name='apply_coupon'),
]

shop/orders/models.py
from itertools import product
from django.db import models
from django.contrib.auth import get_user_model
from home.models import Product
from django.core.validators import MinValueValidator,MaxValueValidator

class Order(models.Model):
      user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='orders')
      paid=models.BooleanField(default=False)
      created=models.DateTimeField(auto_now_add=True)
      updated=models.DateTimeField(auto_now=True)
      discount=models.IntegerField(blank=True,null=True,default=None)

      class Meta:
            ordering=('paid','-updated')

      def __str__(self):
          return f'{str(self.id)}'

      def get_total_price(self):
            total= sum( item.get_cost() for item in self.items.all())
            if self.discount:
                  discount_price=(self.discount / 100)* total
                  return int(total - discount_price)
            return total

class OrderItem(models.Model):
      order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='items')
      product=models.ForeignKey(Product,on_delete=models.CASCADE)
      price=models.IntegerField()
      quantity=models.IntegerField(default=1)

      def __str__(self):
          return str(self.id)

      def get_cost(self):
            return self.quantity * self.price


class Coupon(models.Model):
      code=models.CharField(max_length=30,unique=True)
      valid_from=models.DateTimeField()
      valid_to=models.DateTimeField()
      discount=models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(90)])
      active=models.BooleanField(default=False)

      def __str__(self):
          return self.code

shop/orders/forms.py
import imp
from django import forms


class CartAddForm(forms.Form):
      quantity=forms.IntegerField(min_value=1,max_value=9)

class CouponApplyForm(forms.Form):
      code=forms.CharField()

shop/orders/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from .cart import Cart
from home.models import Product
from .forms import CartAddForm,CouponApplyForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import OrderItem,Order,Coupon
import datetime
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin



class CartView(View):
      def get(self, request):
            cart=Cart(request)
            return render(request,'orders/cart.html',{'cart':cart})


class CartAddView(PermissionRequiredMixin,View):
      permission_required='orders.add_order'
      def post(self,request,product_id):
            cart=Cart(request)
            product=get_object_or_404(Product,id=product_id)
            form=CartAddForm(request.POST)
            if form.is_valid():
                  cart.add(product,form.cleaned_data['quantity'])
            return redirect('orders:cart')

            
class CartRemoveView(View):
      def get(self,request ,product_id):
            cart=Cart(request)
            product=get_object_or_404(Product,id=product_id)
            cart.remove(product)
            return redirect('orders:cart')

class OrderDetailView(LoginRequiredMixin,View):
      form_class=CouponApplyForm
      def get(self,request,order_id):
            order=get_object_or_404(Order,id=order_id)
            return render(request,'orders/order.html',{'order':order,'form':self.form_class})

class OrderCreateView(LoginRequiredMixin,View):
      def get(self,request):
            cart=Cart(request)
            order=Order.objects.create(user=request.user)
            for item in cart:
                  OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
            cart.clear()
            return redirect('orders:order_detail',order.id)

class CouponApplyView(LoginRequiredMixin,View):
      form_class=CouponApplyForm
      def post(self,request,order_id):
            now=datetime.datetime.now()
            form=self.form_class(request.POST)
            if form.is_valid():
                  code=form.cleaned_data['code']
                  try:
                        coupon=Coupon.objects.get(code__exact=code,valid_from__lte=now,valid_to__gte=now,active=True)
                  except coupon.DoesNotExist:
                        messages.error(request,'This coupon does not exist!',extra_tags='danger')
                        return redirect('orders:order_detail',order_id)
                  order=Order.objects.get(id=order_id)
                  order.discount=coupon.discount
                  order.save()
            return redirect('orders:order_detail',order_id)

shop/orders/templates/orders/cart.html
{% extends 'base.html' %}


{% block content %}
      <table class="table table-dark table-striped">
            <thead>
                  <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Unit Price</th>
                        <th scope="col">Total Price</th>
                        <th scope="col">Remove</th>
                  </tr>
            </thead>
            <tbody>
                  {% for item in cart %}
                        <tr>
                              <th scope="row">{{forloop.counter}}</th>
                              <td>{{item.product}}</td>
                              <td>{{item.quantity}}</td>
                              <td>{{item.price}}</td>
                              <td>{{item.total_price}}</td>
                              <td><a href="{% url 'orders:cart_remove' item.product.id %}">Remove</a></td>
                        </tr>
                  {% endfor %}
                  <tr>
                        <td>Total</td>
                        <td colspan="3"></td>
                        <td>{{cart.get_total_price}}</td>
                        <td></td>
                  </tr>
            </tbody>
      </table>
      <a href="{% url 'orders:order_create' %}" class="btn btn-primary" >Check Out</a>
{% endblock %}

shop/orders/templates/orders/order.html
{% extends 'base.html'  %}

{% block content %}

      <h3>Check Out</h3>
      <p>Total Price = {{order.get_total_price}}</p>
      <br>
      <br>
      <form action="{% url 'orders:apply_coupon' order.id %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Apply">
      </form>
{% endblock %}