shop/accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'
urlpatterns = [
      path('register/',views.UserRegisterView.as_view(),name='user_register'),
      path('verify/',views.UserRegisterVerifyCodeView.as_view(),name='verify_code'),
      path('login/',views.UserLoginView.as_view(),name='user_login'),
      path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
]

shop/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('orders/', include('orders.urls',namespace='orders')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns = [
      path('',views.HomeView.as_view(),name='home'),
      path('category/<slug:category_slug>/',views.HomeView.as_view(),name='category_filter'),
      path('<slug:slug>/',views.ProductDetailView.as_view(),name='product_detail'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name='orders'
urlpatterns=[
      path('create/',views.OrderCreateView.as_view(),name='order_create'),
      path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
      path('carts/',views.CartView.as_view(),name='cart'),
      path('carts/add/<int:product_id>',views.CartAddView.as_view(),name='cart_add'),
      path('carts/remove/<int:product_id>',views.CartRemoveView.as_view(),name='cart_remove'),
      path('apply/<int:order_id>/',views.CouponApplyView.as_view(),name='apply_coupon'),
]

shop/templates/inc/messages.html
{% if messages %}
      {% for msg in messages %}
            <p class="alert alert-{{msg.tags}}">{{msg}}</p>
      {% endfor %}
{% endif %}

shop/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
      <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>

            {% if request.user.is_authenticated %}
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_logout' %}">LogOut</a>
            {% else %}
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_register' %}">Register</a>
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_login' %}">Login</a>
                {% endif %}
                <a class="nav-link active" aria-current="page" href="{% url 'orders:cart' %}">Cart {{cart|length}}</a>

        </div>    
      </div>
</nav>